services:
  mybb:
    image: mybb/mybb:latest
    volumes:
    - ./mybb:/var/www/html:rw

  nginx:
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    image: nginx:mainline-alpine
    ports:
    - published: 80
      target: 80
    - published: 443
      target: 443
    volumes:
    - ./nginx:/etc/nginx/conf.d:ro
    - ./mybb:/var/www/html:ro
    - ./data/certbot/conf:/etc/letsencrypt
    - ./data/certbot/www:/var/www/certbot

  postgresql:
    environment:
      POSTGRES_DB: mybb
      POSTGRES_PASSWORD: ${BB_PASS}
      POSTGRES_USER: mybb
    image: postgres:13.2-alpine
    hostname: psqldb
    ports:
    - published: 5432
      target: 5432
    volumes:
    - ./postgres/data:/var/lib/postgresql/data:rw

  certbot:
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt:rw
      - ./data/certbot/www:/var/www/certbot:rw

version: '3.8'
